baseURL = "https://camilla.fitness/"
languageCode = "en-us"
title = "Camilla Fitness"
theme = "clean"

[permalinks]
  page = "/:title/"
  form = "/:slug/"

[[menu.nav]]
  name = "About"
  url = "/about/"
  weight = 5

[[menu.nav]]
  name = "Services"
  url = "/services/"
  weight = 10

[[menu.nav]]
  name = "Testimonials"
  url = "/testimonials/"
  weight = 15

[[menu.nav]]
  name = "Pricing"
  url = "/pricing/"
  weight = 20

[[menu.nav]]
  name = "Contact"
  url = "/contact/"
  weight = 25

[params]  
  socialInstagram = "https://www.instagram.com/camillafitness_pt/"
  subtitle = "Feel good in your body, heart and mind. Camilla Cresswell, Personal Training, Pre & Post Natal & HIIT Classes."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
