baseURL = "https://camilla.fitness/"
languageCode = "en-us"
title = "Camilla Fitness"
theme = "clean"

[permalinks]
page = "/:slug/"
form = "/:slug/"
programs = "/:slug/"

[[menu.nav]]
name = "About"
url = "/about/"
weight = 5

[[menu.nav]]
name = "Services"
url = "/services/"
weight = 10

[[menu.nav]]
name = "Programs"
url = "/programs/"
weight = 15

[[menu.nav]]
name = "Testimonials"
url = "/testimonials/"
weight = 20

[[menu.nav]]
name = "Pricing"
url = "/pricing/"
weight = 25

[[menu.nav]]
name = "Contact"
url = "/contact/"
weight = 30


[[menu.legal]]
name = "Privacy policy"
url = "/privacy/"
weight = 5

[[menu.legal]]
name = "Terms of service"
url = "/terms-of-service/"
weight = 10

[params]
socialInstagram = "https://www.instagram.com/camillafitness_pt/"
subtitle = "Feel good in your body, heart and mind. Camilla Cresswell, Personal Training, Pre & Post Natal & HIIT Classes."
cloudinary_url = "https://res.cloudinary.com/harrycresswell/image/fetch"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
