backend:
  name: git-gateway
  #name: proxy # enable when running the CMS locally. See: https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
  #proxy_url: http://localhost:8081/api/v1 # enable when running teh CMS locally. See: https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
  branch: master # optional, defaults to master
  #branch: testimonials_config # Branch to update (optional; defaults to master)
# This line should *not* be indented
publish_mode: editorial_workflow
# when using the default proxy server port
local_backend: true
# Global media settings
media_library:
  name: cloudinary
  output_filename_only: false
  config:
    cloud_name: harrycresswell
    api_key: 826593925311574
site_url: "https://camilla.fitness/"
slug: # See: https://www.netlifycms.org/docs/configuration-options/#slug-type
  encoding: "ascii" # Sanitize filenames (slugs) according to RFC3986
  clean_accents: true # Remove diacritics from slug characters before sanitizing
  sanitize_replacement: "-" # The replacement string used to substitute unsafe characters
collections:
  - name: "homepage" # Used in routes, e.g., /admin/collections/blog
    label: "Homepage" # Used in the UI
    editor: # the editor view of a collection or a file inside a files collection. See: https://www.netlifycms.org/docs/configuration-options/#editor
      preview: false # disable the preview pane for this collection or file
    files: # Create collection from specific files. See https://www.netlifycms.org/docs/collection-types/#folder-collections
      - label: "Homepage"
        name: "homepage"
        file: "/content/_index.md" # Set path to the file
        fields: # The fields for each document, usually in front matter
          - { label: "Title", name: "title", widget: "string", hint: "Set the page title" }
          - { label: "Date", name: "date", widget: "date" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Insert", name: "insert", widget: "string" }
          - { label: "Image", name: "image", widget: "image", hint: "Add a featured image (this shows on the list page)" }
  - name: "page" # Used in routes, e.g., /admin/collections/blog
    label: "Page" # Used in the UI
    folder: "content/page" # The path to the folder where the documents are stored. See:  https://www.netlifycms.org/docs/collection-types/#folder-collections
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Allow admin to decide the filename and path. See: https://www.netlifycms.org/docs/configuration-options/#slug
    preview_path: "{{slug}}" # The path where content in this collection can be found on the live site. See: https://www.netlifycms.org/docs/configuration-options/#preview_path
    editor: # the editor view of a collection or a file inside a files collection. See: https://www.netlifycms.org/docs/configuration-options/#editor
      preview: false # disable the preview pane for this collection or file
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string", hint: "Add a title for the page" }
      - { label: "Date", name: "date", widget: "date", hint: "Set a publish date" }
      - { label: "Slug", name: "slug", widget: "string", hint: "Set the URL path for the page to link to (eg. /about/)" }
      - { label: "subtitle", name: "subtitle", widget: "string", hint: "Describe the content of the page (this is helps search engines rank the page)" }
      - { label: "Body", name: "body", widget: "markdown" }
       # Add page builder blocks
      - label: "Blocks"
        name: "blocks"
        hint: "Build the rest of the page with content blocks"
        widget: "list"
        typeKey: "component" # Name of the field that will be added to every item in list representing the name of the object widget that item belongs to. Default is “type”.  See: https://www.netlifycms.org/docs/beta-features/#list-widget-variable-types
        # Note that types requires for example - type: image, rather than - template: image. 
        types:
          - label: "Box"
            name: "box"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string", hint: "Add a title for the page" }
              - { label: "Description", name: "description", widget: "string" }
              - { label: "Color", name: "color", widget: "boolean" }
              - { label: "Badge", name: "badge", widget: "boolean" }
              - { label: "Badge text", name: "badge_text", widget: "string" }
              - { label: "Width", name: "width", widget: "select",  options: ["full", "half"] }
  - name: "services" # Used in routes, e.g., /admin/collections/blog
    label: "Services" # Used in the UI
    folder: "content/services" # The path to the folder where the documents are stored. See:  https://www.netlifycms.org/docs/collection-types/#folder-collections
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Allow admin to decide the filename and path. See: https://www.netlifycms.org/docs/configuration-options/#slug
    preview_path: "{{slug}}" # The path where content in this collection can be found on the live site. See: https://www.netlifycms.org/docs/configuration-options/#preview_path
    editor: # the editor view of a collection or a file inside a files collection. See: https://www.netlifycms.org/docs/configuration-options/#editor
      preview: false # disable the preview pane for this collection or file
    fields:
      - { label: "Title", name: "title", widget: "string", hint: "Add a title for the page" }
      - { label: "Date", name: "date", widget: "date", hint: "Set a publish date" }
      - { label: "Description", name: "description", widget: "text", hint: "Describe the content of the page (this is helps search engines rank the page)" }
      - { label: "Subtitle", name: "subtitle", widget: "string", hint: "Describe the content of the page (this is helps search engines rank the page)" }
      - { label: "Slug", name: "slug", widget: "string", hint: "Set the URL path for the page to link to (eg. /personal-training/)" }
      - { label: "Featured image", name: "featured_image", widget: "image", hint: "Add a featured image (this shows on the list page)" }
      - { label: "Featured image alt", name: "featured_image_alt", widget: "string", hint: "Add an alternate text to describe the featured image and improve SEO", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "testimonials" # Used in routes, e.g., /admin/collections/blog
    label: "Testimonials" # Used in the UI
    editor: # the editor view of a collection or a file inside a files collection. See: https://www.netlifycms.org/docs/configuration-options/#editor
      preview: false # disable the preview pane for this collection or file
    files: # Create collection from specific files. See https://www.netlifycms.org/docs/collection-types/#folder-collections
      - label: "Testimonials"
        name: "testimonials"
        file: "data/testimonials.yml" # Set path to the file
        extension: "yml" # Set file extension
        widget: "list"
        fields:
          - { label: "Text", name: "text", widget: "text", hint: "Add the testimonial text" }
          - { label: "Author", name: "author", widget: "string", hint: "Add the testimonial author" }
          # - label: "Testimonial"
          #   name: "testimonial"
          #   widget: "list"
          #   fields:
          #     - { label: "Text", name: "text", widget: "text", hint: "Add the testimonial text" }
          #     - { label: "Author", name: "author", widget: "string", hint: "Add the testimonial author" }
  - name: "form" # Used in routes, e.g., /admin/collections/blog
    label: "Form" # Used in the UI
    folder: "content/form" # The path to the folder where the documents are stored. See:  https://www.netlifycms.org/docs/collection-types/#folder-collections
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Allow admin to decide the filename and path. See: https://www.netlifycms.org/docs/configuration-options/#slug
    preview_path: "{{slug}}" # The path where content in this collection can be found on the live site. See: https://www.netlifycms.org/docs/configuration-options/#preview_path
    editor: # the editor view of a collection or a file inside a files collection. See: https://www.netlifycms.org/docs/configuration-options/#editor
      preview: false # disable the preview pane for this collection or file
    fields:
      - { label: "Title", name: "title", widget: "string", hint: "Add a title for the page" }
      - { label: "Date", name: "date", widget: "date", hint: "Set a publish date" }
      - { label: "Body", name: "body", widget: "markdown" }