---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: content/form
  label: Form
  create: all
  match: "**/*"
- type: directory
  path: data/testimonials.yaml
  label: Testimonials
  create: documents
  match: "**/*"
- type: directory
  path: content/services
  label: Services
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: camillafitness
public_path: https://res.cloudinary.com/harrycresswell/image/upload/f_auto,q_auto,w_auto,dpr_auto,c_scale
front_matter_path: https://res.cloudinary.com/harrycresswell/image/upload/f_auto,q_auto,w_auto,dpr_auto,c_scale
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.63.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.63.2
