---
label: services
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: text
  name: subtitle
  label: subtitle
- type: field_group_list
  name: blocks
  label: blocks
  fields:
  - type: text
    name: component
    label: component
    hidden: true
  - type: datetime
    name: title
    label: title
  - name: featured_image
    type: file
    config:
      maxSize: 64
    label: Featured image
  - type: text
    name: description
    label: description
  - type: text
    name: link
    label: link
pages:
- content/services.md
